# Generated by Django 2.1.5 on 2020-03-27 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuisine',
            fields=[
                ('cuisine_type', models.CharField(max_length=200, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='recipe_images')),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('recipe_id', models.AutoField(primary_key=True, serialize=False)),
                ('recipe_name', models.CharField(max_length=128)),
                ('time_taken', models.IntegerField()),
                ('level', models.IntegerField()),
                ('ingredients', models.TextField(max_length=1000)),
                ('cooking_type', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=2000)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('cuisine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakingbread.Cuisine')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('report_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_type', models.IntegerField()),
                ('reported_user', models.TextField(blank=True, max_length=200, null=True)),
                ('post', models.TextField(blank=True, max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('status', models.BooleanField(default=False)),
                ('action_taken', models.CharField(blank=True, max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified', models.DateTimeField()),
                ('recipe_id', models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='breakingbread.Recipe')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('rating', models.IntegerField(default=0)),
                ('description', models.TextField(max_length=500)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('active', models.BooleanField(default=False)),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakingbread.Recipe')),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.IntegerField(default=0)),
                ('address', models.CharField(blank=True, max_length=300)),
                ('address_hidden', models.BooleanField(default=False)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='report',
            name='review_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET(None), to='breakingbread.Review'),
        ),
        migrations.AddField(
            model_name='report',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakingbread.Recipe'),
        ),
    ]
