# Generated by Django 2.1.5 on 2020-02-26 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakingbread', '0003_auto_20200225_1613'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('image_id', models.AutoField(primary_key=True, serialize=False)),
                ('picture', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image4',
        ),
        migrations.RemoveField(
            model_name='recipe',
            name='image5',
        ),
        migrations.AddField(
            model_name='image',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breakingbread.Recipe'),
        ),
    ]
