# Generated by Django 2.1.5 on 2020-03-11 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakingbread', '0005_remove_recipe_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to='recipe_images'),
        ),
    ]
