# Generated by Django 2.1.5 on 2020-03-12 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakingbread', '0007_recipe_average_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='average_rating',
        ),
    ]
