# Generated by Django 2.1.5 on 2020-03-17 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakingbread', '0008_remove_recipe_average_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
