# Generated by Django 2.1.5 on 2020-03-17 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breakingbread', '0009_recipe_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='slug',
        ),
    ]
