# Generated by Django 2.1.5 on 2020-03-22 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breakingbread', '0011_auto_20200322_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['created']},
        ),
        migrations.AddField(
            model_name='review',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
