# Generated by Django 2.1.5 on 2020-03-27 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('breakingbread', '0013_auto_20200322_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='post_id',
        ),
        migrations.AddField(
            model_name='report',
            name='recipe_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakingbread.Recipe'),
        ),
        migrations.AddField(
            model_name='report',
            name='review_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='breakingbread.Review'),
        ),
    ]
